### ISSUE TITLE
Flaky tests in TaskRepository

### ISSUE THREAD

**Issue by davydovanton** [ossboard-org/ossboard#127]
We have [flaky tests](https://github.com/nodejs/node/wiki/Flaky-tests) and we need to fix it

```
1) TaskRepository#all_from_date returns array of tasks
   Failure/Error: expect(repo.all_from_date(date).count).to eq 8
     expected: 8
          got: 16
     (compared using ==)
   # ./spec/ossboard/repositories/task_repository_spec.rb:176:in `block (3 levels) in <top (required)>'
   # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.4/lib/rspec/retry.rb:112:in `block in run'
   # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.4/lib/rspec/retry.rb:101:in `loop'
   # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.4/lib/rspec/retry.rb:101:in `run'
   # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.4/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
   # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.4/lib/rspec/retry.rb:30:in `block (2 levels) in setup'
2) TaskRepository#all_from_date should eq 2
   Failure/Error: it { expect(repo.all_from_date(date, 'in progress').count).to eq 2 }
     expected: 2
          got: 10
     (compared using ==)
   # ./spec/ossboard/repositories/task_repository_spec.rb:178:in `block (3 levels) in <top (required)>'
   # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.4/lib/rspec/retry.rb:112:in `block in run'
   # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.4/lib/rspec/retry.rb:101:in `loop'
   # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.4/lib/rspec/retry.rb:101:in `run'
   # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.4/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
   # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.4/lib/rspec/retry.rb:30:in `block (2 levels) in setup'
```

And one more
```
1) Admin::Views::Users::Index#banned_users should eq []
   Failure/Error: it { expect(view.banned_users).to eq [] }
     expected: []
          got: ["anton3", "anton2", "anton1"]
     (compared using ==)
   # ./spec/admin/views/users/index_spec.rb:32:in `block (3 levels) in <top (required)>'
   # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.4/lib/rspec/retry.rb:112:in `block in run'
   # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.4/lib/rspec/retry.rb:101:in `loop'
   # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.4/lib/rspec/retry.rb:101:in `run'
   # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.4/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
   # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.4/lib/rspec/retry.rb:30:in `block (2 levels) in setup'
```

**Comment by davydovanton** [comment]
Fixed by https://github.com/ossboard-org/ossboard/pull/141
